name: agriadvisor
description: Application mobile Flutter AgriAdvisor
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"  # Version plus récente

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0           # Version plus stable
  shared_preferences: ^2.2.2  # AJOUTÉ
  fluttertoast: ^9.0.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tomate.jpg
    - assets/images/poivron.jpg
    - assets/images/mil.jpg
    - assets/images/arachide.jpeg
    - assets/images/serre.jpg
    - assets/images/plein_air.jpeg