name: semence_smart
description: Application mobile Semence Smart
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  font_awesome_flutter: ^10.7.0

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  
  # Maps & Location
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  
  # State Management & API
  provider: ^6.1.1
  http: ^1.6.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Notifications
  fluttertoast: ^8.2.4
  flutter_svg: ^2.3.0
  flutter_local_notifications: ^22.2.0
  
  # Audio (synthèse vocale) - Commenté pour l'instant
  # just_audio: ^0.10.5
  # path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/tomate.jpg
    - assets/images/poivron.jpg
    - assets/images/mil.jpg
    - assets/images/arachide.jpeg
    - assets/images/serre.jpg
    - assets/images/plein_air.jpeg
    - .env